[phases.setup]
aptPkgs = ["libgl1", "libglib2.0-0", "libxcb1", "libx11-6", "libxrender1", "libxext6", "libx11-xcb1", "libdbus-1-3"]

[phases.install]
cmds = ["...", ". /opt/venv/bin/activate && pip uninstall -y opencv-python opencv-python-headless && pip install opencv-python-headless"]
